# Custom Language File for Launcher Customizer

[ejs.app]
title = "Heopop Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "어서오세요!"
welcomeDescription = "해당 런처는 자체 제작한 런처입니다. 2차 수정, 2차 배포는 금지합니다. 허팝 컨텐츠 전용 런처입니다. 다른 용도로 사용하시면 법적 처벌을 받으실 수 있습니다."
welcomeDescCTA = ""
